//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G1_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class US
    {
        public string ProductID { get; set; }
        public string MaterialID { get; set; }
        public string GoesIntoQuantity { get; set; }
        public string UsesID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual RAWMATERIAL RAWMATERIAL { get; set; }
    }
}
